### ISSUE TITLE
Compile Issue

### ISSUE THREAD

**Issue by dawsdep** [joshnuss/phoenix-billing-demo#4]
I cloned the repo, installed the dependencies, and ran mix phoenix.server and it gave me a compile error as follows:

== Compilation error on file web/router.ex ==
** (CompileError) web/router.ex: internal error in v3_core;
crash reason: {case_clause,
    {'EXIT',
        {badarg,
            [{erl_anno,anno_info,[-1],[{file,"erl_anno.erl"},{line,360}]},
             {v3_core,record_anno,2,[{file,"v3_core.erl"},{line,2410}]},
             {v3_core,expr,2,[{file,"v3_core.erl"},{line,539}]},
             {v3_core,safe,2,[{file,"v3_core.erl"},{line,1593}]},
             {v3_core,expr,2,[{file,"v3_core.erl"},{line,528}]},
             {v3_core,safe,2,[{file,"v3_core.erl"},{line,1593}]},
             {v3_core,'-safe_list/2-anonymous-0-',2,
                 [{file,"v3_core.erl"},{line,1608}]},
             {lists,foldr,3,[{file,"lists.erl"},{line,1276}]},
             {v3_core,expr,2,[{file,"v3_core.erl"},{line,538}]},
             {v3_core,safe,2,[{file,"v3_core.erl"},{line,1593}]},
             {v3_core,'-safe_list/2-anonymous-0-',2,
                 [{file,"v3_core.erl"},{line,1608}]},
             {lists,foldr,3,[{file,"lists.erl"},{line,1276}]},
             {v3_core,expr,2,[{file,"v3_core.erl"},{line,538}]},
             {v3_core,safe,2,[{file,"v3_core.erl"},{line,1593}]},
             {v3_core,expr,2,[{file,"v3_core.erl"},{line,528}]},
             {v3_core,safe,2,[{file,"v3_core.erl"},{line,1593}]},
             {v3_core,'-safe_list/2-anonymous-0-',2,
                 [{file,"v3_core.erl"},{line,1608}]},
             {lists,foldr,3,[{file,"lists.erl"},{line,1276}]},
             {v3_core,expr,2,[{file,"v3_core.erl"},{line,652}]},
             {v3_core,exprs,2,[{file,"v3_core.erl"},{line,512}]}]}}}

  in function  compile:'-select_passes/2-anonymous-2-'/2 (compile.erl, line 536)
  in call from compile:'-internal_comp/4-anonymous-1-'/2 (compile.erl, line 321)
  in call from compile:fold_comp/3 (compile.erl, line 347)
  in call from compile:internal_comp/4 (compile.erl, line 331)
  in call from compile:'-do_compile/2-anonymous-0-'/2 (compile.erl, line 179)
    (stdlib) lists.erl:1338: :lists.foreach/2
    (phoenix) expanding macro: Phoenix.Router.__before_compile__/1
    web/router.ex:1: Store.Router (module)
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1

**Comment by joshnuss** [comment]
Probably a version issue, I will check it out

Thanks for reporting.

**Comment by joshnuss** [comment]
I updated all the dependencies and it's now working. Pull the latest version and let me know if you bump into anything else.

Cheers!

**Comment by dawsdep** [comment]
Thank you! It's compiling and working now.

There are quite a few warnings about versions being depreciated.

I got this message:
(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.

and was shown some JS and C stack traces.

But I was mainly just looking to see an example of stripe working with Elixir and Phoenix and this is going to do that job perfectly. Thanks for being so quick, it helps a lot.

**Comment by joshnuss** [comment]
Welcome!

It's probably something with your node version. I wouldn't worry about it, the project doesn't rely on any client side JavaScript.

Cheers!
